[package]
name = "fortress-codegen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
fortress-ast.workspace = true
fortress-types.workspace = true
inkwell = { version = "0.10.0", default-features = false, features = ["llvm22-1"] }

[lints]
workspace = true
